[workspace]
resolver = "2"
members = [
    "core/seisbox_core",
    "apps/seisbox_launcher",
    "apps/seisbox_picker",
    "apps/seisbox_stats",
    "apps/seisbox_hvsr",
    "apps/seisbox_inversion",
    "apps/seisbox_cfs",
    "apps/seisbox_interp",
    "apps/seisbox_fdsn",
    "apps/seisbox_isc",
]

[workspace.dependencies]
eframe = "0.31"
egui_plot = "0.31"
egui_extras = { version = "0.31", features = ["image"] }
rfd = "0.15"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
sacio = "0.1.0"
miniseed-rs = "0.2.1"
rustfft = "6.4.1"
sci-rs = "0.4.1"
image = "0.24"
chrono = "0.4.45"
shapefile = "0.8.0"
reqwest = { version = "0.13.4", features = ["blocking"] }
csv = "1.4.0"
plotters = "0.3.5"
rand = "0.8.5"
rand_distr = "0.4.3"
serde_json = "1.0.150"
tempfile = "3.27.0"
kiddo = "5.3.2"
geo = "0.28.0"
statrs = "0.18.0"
rayon = "1.12.0"
npyz = "0.9.1"
zip = "8.6.0"
tiff = { version = "0.11.3", default-features = false }
nalgebra = "0.35.0"
directories = "5.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

[profile.dev]
overflow-checks = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 8
panic = "abort"
strip = "symbols"
