[package]
name = "seisbox_interp"
version = "0.1.1"
edition = "2021"

[dependencies]
seisbox_core = { path = "../../core/seisbox_core" }
eframe = { workspace = true }
egui_plot = { workspace = true }
egui_extras = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rfd = { workspace = true }
csv = { workspace = true }
