[package]
name = "seisbox_cfs"
version = "0.1.2"
edition = "2021"

[dependencies]
seisbox_core = { path = "../../core/seisbox_core" }
eframe = { workspace = true }
egui_plot = { workspace = true }
egui_extras = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rfd = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
csv = { workspace = true }
plotters.workspace = true
contour = "0.13.1"
geo = { workspace = true }
rayon = { workspace = true }
clap = { workspace = true }
