#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

pub mod cli;
pub mod core;
pub mod io;
pub mod ui;

use clap::Parser;
use eframe::egui;
use std::path::PathBuf;
use ui::hvsr_dialog::{HvsrDialogState, show_hvsr_app};
use crate::core::math_hvsr::{HvsrParams, HvsrProgress, process_hvsr_pipeline};

pub struct SeisboxHvsrApp {
    state: HvsrDialogState,
}

impl Default for SeisboxHvsrApp {
    fn default() -> Self {
        Self {
            state: HvsrDialogState::default(),
        }
    }
}

impl eframe::App for SeisboxHvsrApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        show_hvsr_app(ctx, &mut self.state);
    }
}

fn run_headless(files: Vec<PathBuf>, args: cli::Cli) {
    println!("Running headless HVSR processing...");
    let mut z = None;
    let mut n = None;
    let mut e = None;
    for path in files {
        if let Ok(seismograms) = seisbox_core::core::parser::parse_seismic_file(&path) {
            for seis in seismograms {
                let ch = if seis.channel.trim().is_empty() {
                    &seis.filename
                } else {
                    &seis.channel
                };
                
                let ch_upper = ch.to_uppercase();
                
                if ch_upper.ends_with('Z') || ch_upper.ends_with("Z.SAC") { z = Some(seis.clone()); }
                else if ch_upper.ends_with('N') || ch_upper.ends_with("N.SAC") || ch_upper.ends_with('1') || ch_upper.ends_with("1.SAC") { n = Some(seis.clone()); }
                else if ch_upper.ends_with('E') || ch_upper.ends_with("E.SAC") || ch_upper.ends_with('2') || ch_upper.ends_with("2.SAC") { e = Some(seis.clone()); }
            }
        }
    }
    
    if let (Some(zs), Some(ns), Some(es)) = (z, n, e) {
        let dt = 1.0 / zs.sample_rate;
        let mut z_data = zs.amplitude;
        let mut n_data = ns.amplitude;
        let mut e_data = es.amplitude;
        
        crate::core::math_hvsr::detrend_signal(&mut z_data);
        crate::core::math_hvsr::detrend_signal(&mut n_data);
        crate::core::math_hvsr::detrend_signal(&mut e_data);
        
        if args.hvtfa {
            println!("Running HVTFA analysis...");
            let res = crate::core::math_hvtfa::run_hvtfa(
                &z_data, &n_data, &e_data, 1.0 / dt,
                args.freq_min, args.freq_max, args.freq_count, args.hvtfa_m, None
            );
            
            if let Some(out_path) = &args.output {
                let max_path = out_path.with_extension("max");
                let mut content = String::from("# File generated by SeisBox HVTFA\n# seconds from start | cfreq | H/V\n");
                for p in &res.scatter_points {
                    content.push_str(&format!("{:.5} {:.5} {:.5}\n", p.time, p.freq, p.hv_neg));
                    content.push_str(&format!("{:.5} {:.5} {:.5}\n", p.time, p.freq, p.hv_pos));
                }
                if let Err(e) = std::fs::write(&max_path, content) {
                    eprintln!("Error writing max file: {}", e);
                } else {
                    println!("Successfully exported scatter points to {}", max_path.display());
                }
                
                let target_path = out_path.with_extension("target");
                let mut target_content = String::from("# Frequency(Hz) | Mean_H/V | Log_StdDev\n");
                for p in &res.picked_curve {
                    target_content.push_str(&format!("{:.5} {:.5} {:.5}\n", p.freq, p.hv_mode, p.hv_std_log));
                }
                if let Err(e) = std::fs::write(&target_path, target_content) {
                    eprintln!("Error writing target file: {}", e);
                } else {
                    println!("Successfully exported picked curve to {}", target_path.display());
                }
                
                if args.plot_curve {
                    let mut plot_path = out_path.clone();
                    plot_path.set_file_name(format!("{}_hvtfa.png", out_path.file_stem().unwrap_or_default().to_string_lossy()));
                    println!("Generating HVTFA plot to {}...", plot_path.display());
                    if let Err(e) = crate::io::plotters_export::export_hvtfa_plot(
                        &plot_path, args.freq_min, args.freq_max, &res.scatter_points, &res.picked_curve
                    ) {
                        eprintln!("Error plotting HVTFA: {}", e);
                    }
                }
            }
            return;
        }
        
        let combine_method = match args.combine {
            cli::CombineMethod::Geometric => crate::core::math_hvsr::HorizontalCombineMethod::Geometric,
            cli::CombineMethod::Quadratic => crate::core::math_hvsr::HorizontalCombineMethod::Quadratic,
            cli::CombineMethod::Arithmetic => crate::core::math_hvsr::HorizontalCombineMethod::Arithmetic,
            cli::CombineMethod::Maximum => crate::core::math_hvsr::HorizontalCombineMethod::Maximum,
            cli::CombineMethod::Dfa => crate::core::math_hvsr::HorizontalCombineMethod::Dfa,
        };
        
        let params = HvsrParams {
            window_len_s: args.window_len,
            overlap_pct: args.overlap,
            sta_len_s: args.sta_len,
            lta_len_s: args.lta_len,
            t1: args.t1,
            t2: args.t2,
            b_value: args.b_value,
            freq_min: args.freq_min,
            freq_max: args.freq_max,
            freq_count: args.freq_count,
            combine_method,
            enable_f0_filter: args.f0_filter,
            f0_filter_n: args.f0_filter_n,
        f0_filter_max_iter: args.f0_filter_max_iter,
        };
        
        println!("Computing windows...");
        let windows = match crate::core::math_hvsr::compute_windows(&z_data, &n_data, &e_data, dt, &params) {
            Ok(w) => w,
            Err(e) => {
                eprintln!("Error computing windows: {}", e);
                return;
            }
        };
        
        let plot_z = if args.plot_windows { Some(z_data.clone()) } else { None };
        let plot_n = if args.plot_windows { Some(n_data.clone()) } else { None };
        let plot_e = if args.plot_windows { Some(e_data.clone()) } else { None };
        
        let (tx, rx) = std::sync::mpsc::channel();
        std::thread::spawn(move || {
            process_hvsr_pipeline(z_data, n_data, e_data, dt, params, windows, tx);
        });
        
        let mut result = None;
        while let Ok(msg) = rx.recv() {
            match msg {
                HvsrProgress::Progress(pct, s) => {
                    println!("[{:.1}%] {}", pct * 100.0, s);
                }
                HvsrProgress::Error(e) => {
                    eprintln!("Pipeline Error: {}", e);
                    return;
                }
                HvsrProgress::Complete(res) => {
                    result = Some(res);
                    break;
                }
                HvsrProgress::HvtfaComplete(_) => {
                    eprintln!("HVTFA complete via CLI is not supported yet.");
                    break;
                }
            }
        }
        
        if let Some(res) = result {
            if let Some(ref out_path) = args.output {
                let final_stats = if let Some(f0) = &res.f0_stats { f0 } else { &res.sta_lta_stats };
                let mut peak_amp = 0.0;
                for &val in &final_stats.mean_hvsr {
                    if val > peak_amp { peak_amp = val; }
                }
                
                let mut csv_content = String::new();
                csv_content.push_str(&format!("# f0 from average\t{:.4}\n", final_stats.f0_mean));
                csv_content.push_str(&format!("# Peak amplitude\t{:.4}\n", peak_amp));
                if let Some(sesame) = &res.sesame_result {
                    csv_content.push_str(&format!("# SESAME Reliable\t{}\n", sesame.is_reliable));
                    csv_content.push_str(&format!("# SESAME Clear Peak\t{}\n", sesame.is_clear_peak));
                    csv_content.push_str(&format!("# SESAME Rel_c1\t{}\n", sesame.reliability_c1));
                    csv_content.push_str(&format!("# SESAME Rel_c2\t{}\n", sesame.reliability_c2));
                    csv_content.push_str(&format!("# SESAME Rel_c3\t{}\n", sesame.reliability_c3));
                    csv_content.push_str(&format!("# SESAME Clr_c1\t{}\n", sesame.clear_peak_c1));
                    csv_content.push_str(&format!("# SESAME Clr_c2\t{}\n", sesame.clear_peak_c2));
                    csv_content.push_str(&format!("# SESAME Clr_c3\t{}\n", sesame.clear_peak_c3));
                    csv_content.push_str(&format!("# SESAME Clr_c4\t{}\n", sesame.clear_peak_c4));
                    csv_content.push_str(&format!("# SESAME Clr_c5\t{}\n", sesame.clear_peak_c5));
                    csv_content.push_str(&format!("# SESAME Clr_c6\t{}\n", sesame.clear_peak_c6));
                }
                csv_content.push_str("Frequency,Mean_HV,Std_Dev_Plus,Std_Dev_Minus\n");
                
                for i in 0..res.freq.len() {
                    csv_content.push_str(&format!("{:.4},{:.4},{:.4},{:.4}\n",
                        res.freq[i], final_stats.mean_hvsr[i], final_stats.std_plus[i], final_stats.std_minus[i]));
                }
                if let Err(e) = std::fs::write(&out_path, csv_content) {
                    eprintln!("Error writing output: {}", e);
                } else {
                    println!("Successfully exported to {}", out_path.display());
                }
            } else {
                println!("Processing complete. No output file specified (-o/--output).");
            }

            // Export plots
            if args.plot_curve {
                let out_png = args.output.clone().unwrap_or_else(|| PathBuf::from("hvsr_curve.png")).with_extension("png");
                println!("Generating HVSR curve plot to {}...", out_png.display());
                let final_stats = if let Some(f0) = &res.f0_stats { f0 } else { &res.sta_lta_stats };
                if let Err(e) = io::plotters_export::export_hvsr_curve(
                    &out_png,
                    &res.freq,
                    final_stats,
                    &res.all_hvsr,
                    &res.final_valid_idx.iter().enumerate().filter_map(|(i, &v)| if v { Some(i) } else { None }).collect::<Vec<_>>(),
                    args.combine == cli::CombineMethod::Dfa,
                ) {
                    eprintln!("Failed to export curve plot: {}", e);
                }
            }

            if args.plot_windows {
                if let (Some(pz), Some(pn), Some(pe)) = (plot_z, plot_n, plot_e) {
                    let out_png = args.output.clone().unwrap_or_else(|| PathBuf::from("hvsr_windows.png")).with_file_name(
                        args.output.as_ref().map(|p| p.file_stem().unwrap().to_string_lossy().to_string() + "_windows").unwrap_or_else(|| "hvsr_windows".to_string())
                    ).with_extension("png");
                    
                    println!("Generating time series window plot to {}...", out_png.display());
                    if let Err(e) = io::plotters_export::export_hvsr_windows(
                        &out_png,
                        &pz, &pn, &pe,
                        1.0 / dt,
                        &res.window_starts_s,
                        args.window_len,
                        &res.final_valid_idx,
                    ) {
                        eprintln!("Failed to export windows plot: {}", e);
                    }
                }
            }
        }
    } else {
        eprintln!("Error: Could not find all 3 components (Z, N, E) in the provided files.");
    }
}

fn main() -> Result<(), eframe::Error> {
    tracing_subscriber::fmt::init();
    
    let mut args = cli::Cli::parse();
    if args.files.is_some() {
        let files = args.files.clone().unwrap();
        run_headless(files, args);
        return Ok(());
    }
    
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default().with_inner_size([1200.0, 800.0]),
        ..Default::default()
    };
    
    eframe::run_native(
        "SeisBox HVSR Analysis",
        options,
        Box::new(|cc| {
            cc.egui_ctx.set_visuals(egui::Visuals::light());
            Ok(Box::new(SeisboxHvsrApp::default()))
        }),
    )
}
